### ISSUE TITLE
Resources not generated when no source code in a project

### ISSUE THREAD

**Issue by Omertron** [ktoso/maven-git-commit-id-plugin#190]
I have a multi project repo with 5 sub-projects. ( https://github.com/YAMJ/yamj-v3 )
For each of the sub-projects with code (common/core/filescanner/jetty) the src/main/resources/version.txt file is correctly filtered and placed in the target/classes directory.

For the "distribution" project (with no classes), the file is not filtered at all.

**Comment by TheSnoozer** [comment]
Hi @Omertron,
Thanks for reporting this issue.
I just finished my research on this one and discovered two different kind of problems.

1) With your current configuration the git-commit-id-plugin will not be executed for the yamj3-distribution. To bypass this problem I added the configuration-Option ``<skipPoms>false</skipPoms>`` to the git-commit-id-plugin parent-pom's configuration. According to the readme, this property is set to ``true`` by default and will skip the execution of the git-commit-id-plugin (the yamj3-distribution-project has the packing pom).

Quote from readme:
```
<!--
                        this is true by default; You may want to set this to false, if the plugin should run inside a
                        <packaging>pom</packaging> project. Most projects won't need to override this property.

                        For an use-case for this kind of behaviour see: https://github.com/ktoso/maven-git-commit-id-plugin/issues/21
                    -->
                    <skipPoms>true</skipPoms>
```

2) Somehow the maven-resources-plugin will not be executed for the yamj3-distribution-project. I'm not sure why, but I assume this is also due to the fact of the ``pom``-packaging option. So what will happen is quite simple: Due to the fact that the maven-resources-plugin is not running it will save a filtered file of the "versions.txt" under target/classes. If you search the target-directory for the versions.txt it will not yield any results. However, according to the assembly-bin it will try to get a versions-File from ``${project.build.directory}/classes``. The folder and the file does not exists and therefore will not be included in the assembly. To bypass this issue I added the execution of the  maven-resources-plugin to the yamj3-distribution-pom like this:
```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-resources-plugin</artifactId>
  <version>2.7</version>
  <executions>
    <execution>
    <id>default-resources</id>
    <phase>process-resources</phase>
    <goals>
      <goal>resources</goal>
    </goals>
  </execution>
  </executions>
</plugin>
```
In the final end the filted versions.txt will be stored in ``${project.build.directory}/classes`` and will be added to the assembly.
Again I'm not 100% why the maven-resources-plugin is not filtering the resources for a ``pom``-packinging project and there might be some additional parameters to force the execution.
My suggestion is just a workaround but leads to the goal you hopefully want to achive.

If you have figured out some other way, please let me know and I hope this helps.

**Comment by Omertron** [comment]
Hi @TheSnoozer, thank you so much for taking the time to look into the issue.

I did spot the "skipPoms" setting but I read the default as "false" and therefore had discounted it, but did mean to test it and see if that was an (the) issue.

I can confirm that it works as expected with the addition of the `maven-resources-plugin`

**Comment by TheSnoozer** [comment]
Hi @Omertron,
glad to hear that this resolves your issue :)
Happy coding!
