### ISSUE TITLE
Plugin fails on simple project

### ISSUE THREAD

**Issue by rpomeroy** [ktoso/maven-git-commit-id-plugin#196]
https://github.com/rpomeroy/rjp-test

Fails with the following stack trace related to slf4j:  https://gist.github.com/rpomeroy/bba52d8aed21004ebb1e#file-gistfile1-txt

Any guidance appreciated

**Comment by TheSnoozer** [comment]
Hi @rpomeroy ,
thanks for reporting this issue!
This is a must fix for the next version.

A quick online search yielded a similar problem (https://jira.codehaus.org/browse/MNG-5787).
I need to figure out if we can go for a workaround or if this is an issue within maven...
The only available solution I have to your problem is to use the older version of the git-commit-id-plugin (2.1.13). We have introduced the slf4j-Logger in the 2.1.14 and somehow it seems that maven does not handle something correctly.


Based on the snippet you had posted you are currently using:
maven-3.3.3
jdk1.8.0_25.jdk
on a mac, right?

Thanks,

**Comment by rpomeroy** [comment]
Correct.  

> Based on the snippet you had posted you are currently using:
> maven-3.3.3
> jdk1.8.0_25.jdk
> on a mac, right?
> 
> Thanks,
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/ktoso/maven-git-commit-id-plugin/issues/196#issuecomment-106919851>.
> 

--
Ronald Pomeroy
rpomeroy@me.com

**Comment by ktoso** [comment]
Whoa sounds bad. Maybe we could get away with jarjar ing... Will have a
look at it as well.

Thanks for reporting

**Comment by TheSnoozer** [comment]
Well at least and can now reproduce the issue with
```
java version "1.8.0_45"
java version "1.7.0_80"
```
and
```
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /usr/share/maven-3.3.3
OS name: "linux", version: "3.16.0-33-generic", arch: "amd64", family: "unix"
```
and it seem that this MNG-5787 is the same issue.
it breaks with different java-versions on different operating systems.
We can either use the 
https://maven.apache.org/plugins/maven-shade-plugin/
or https://maven.apache.org/plugins/maven-assembly-plugin/
to somehow fix it....

**Comment by TheSnoozer** [comment]
Well, it really seems that org.slf4j is the only dependency that currently creates the problem.
At least the workaround by creating a shaded war only need to have the org.slf4j-classes.

Workaround tested with mvn3.3.3, mvn3.2.3, mvn3.1.1 and each maven version tested with
``
java version "1.6.0_45" (java 6 is not supported with mvn3.3.3)
java version "1.7.0_80"
java version "1.8.0_45"
``

**Comment by TheSnoozer** [comment]
Hi @rpomeroy,
this issue is fixed by https://github.com/ktoso/maven-git-commit-id-plugin/pull/197
Thanks for reporting :-)
