### ISSUE TITLE
Support system properties

### ISSUE THREAD

**Issue by tweise** [ktoso/maven-git-commit-id-plugin#208]
It would be great if the plugin configuration can support system properties that can be passed from the command line or set dynamically.

**Comment by TheSnoozer** [comment]
Hi @tweise,
thanks for letting us know further improvements of the plugin.
What properties would you like to set all plugin-configuration-options via command line?
Not sure if it's reasonable to add this behavior inside the plugin, so far I haven't seen a single maven plugin doing this (I can check this out anyway ;-)). Also need to investigate if it's good behavior to bypass the pom.xml-config based on System parameters. Also what happens if we have multiple configurations of the plugin in child pom's. Would you like to override all executions of the maven-git-commit-id plugin? Maybe, maybe not....
Also what happens if another plugin checks for the the command-line-arguments and we interfere with its execution?

Well you see a lot of question arise when actually thinking about this :-)
Nevertheless in case there are only some properties you would like to override you can go for this workaround:
```xml
<properties>
  <git.commit.plugin.properties.file>target/testing.properties</git.commit.plugin.properties.file>
</properties>
....
<plugin>
            <groupId>pl.project13.maven</groupId>
            <artifactId>git-commit-id-plugin</artifactId>
            <executions>
              <execution>
                <goals>
                  <goal>revision</goal>
                </goals>
              </execution>
            </executions>
            <configuration
             <generateGitPropertiesFilename>${git.commit.plugin.properties.file}</generateGitPropertiesFilename>
            </configuration>
          </plugin>
```

You could override this with:
```
mvn clean package -Dgit.commit.plugin.properties.file=target/yournewFile.properties
```

**Comment by ktoso** [comment]
This should not be part of the plugin - this is exactly what maven properties are for, as @TheSnoozer has shown in the later example. 

Voting to close, it's solved by how maven works - just use properties for values you want to configure this way.

**Comment by TheSnoozer** [comment]
@ktoso agree. I'll put it on the graveyard.

**Comment by tweise** [comment]
There are several plugins that support properties, here is another example:

https://maven.apache.org/plugins/maven-dependency-plugin/build-classpath-mojo.html

```
<properties>
  <git.commit.plugin.properties.file>target/testing.properties</git.commit.plugin.properties.file>
</properties>
...
<generateGitPropertiesFilename>${git.commit.plugin.properties.file}</generateGitPropertiesFilename>
```
With property support you could do instead:
```
-Drevision.generateGitPropertiesFilename=...
``` 
It would also allow to set properties during the build (profile activation options are very limited). Plugin configuration section is resolved before any other plugin runs.

**Comment by TheSnoozer** [comment]
Hi @tweise,
the properties could be overwritten with the activation of a profile:
```xml
<!-- global properties for the pom -->
<properties>
  <git.commit.plugin.properties.file>target/testing.properties</git.commit.plugin.properties.file>
</properties>

<!-- global execution definition of the plugin -->
<plugin>
  <groupId>pl.project13.maven</groupId>
  <artifactId>git-commit-id-plugin</artifactId>
  <executions>
    <execution>
      <goals>
        <goal>revision</goal>
      </goals>
    </execution>
  </executions>
  <configuration>
    <generateGitPropertiesFilename>${git.commit.plugin.properties.file}</generateGitPropertiesFilename>
  </configuration>
</plugin>

<!-- customer Profile -->
<profile>
  <id>demo</id>
  <properties
    <git.commit.plugin.properties.file>target/customerFoo.properties</git.commit.plugin.properties.file>
  </properties>
</profile>
```

as soon as I build with ``mvn clean package -Pdemo`` the git-commit-id-plugin will generate it's content to the file that is specified in the profile. And you still can overrule everything with using ``-Dgit.commit.plugin.properties.file=target/somethingDifferent``
