### ISSUE TITLE
Provide code style description for auto-formatting

### ISSUE THREAD

**Issue by szymex** [ktoso/maven-git-commit-id-plugin#214]
Provide code style description for auto-formatting, for example .idea/codeStyleSettings.xml for IntelliJ IDEA users.

**Comment by TheSnoozer** [comment]
I like this. 
Thought about this a couple of times, because I use this in my private projects as well.
Not sure if this code style description will also be taken into account when you use a different IDE like eclipse, sts or netbeans. 
Would definitely prefer something that works more than for just one IDE.
Otherwise this projects ends up with huge amount of different code style descriptions that also needs to be maintained.

**Comment by ktoso** [comment]
`+1` for a code formatter, if we can find one that just works independently of IDE.
`-1` for anything IDE specific. Not all contributors use IDEA and thus would mess up the formatting anyway, rendering the settings useless...

Status quo of the java formatting landscape seems to be that only the eclipse formatter can be used from a maven plugin: https://github.com/revelc/formatter-maven-plugin/issues/35
So I'm slightly hesitant...

**Comment by autayeu** [comment]
An option: piggyback on Google Code Style, for example just by referring "Source code is formatted following Google Code Style for Java: https://google.github.io/styleguide/javaguide.html

Google Code Style for Java can be imported into IDEA and into Eclipse. These two IDEs cover many developers.

**Comment by ktoso** [comment]
I mean an automated formatter. We can agree and it'll work for the 2-3 of us, however this project has a vast number of contributors, which come in with their styles. 

The formatting should be automated - would you be able to pull that in as part of the build @autayeu? Thanks.

**Comment by autayeu** [comment]
Perhaps automated formatting could be approached as a two-step process: a check and a reference to a well-known style guide. For example, CheckStyle can alert the developer responsible for the change and that developer can then fix the formatting using developer's favorite method according to the style guide. Then, a well-known style guide most likely has settings for most popular IDEs ;) and everybody is happy.

**Comment by TheSnoozer** [comment]
+1 still for this issue
http://checkstyle.sourceforge.net/
https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/custom-checker-config.html
https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml
for me it looks wrong to just adopt a style from a different project...

regardless this seems to be a right approach plus by now there are plugins available for various different IDE's:
https://plugins.jetbrains.com/plugin/1065-checkstyle-idea
https://marketplace.eclipse.org/content/checkstyle-plug
http://plugins.netbeans.org/plugin/3413/checkstyle-beans

**Comment by TheSnoozer** [comment]
I have integrated checkstyle into this project.
The rules are getting checked with travis and thus will be verified for every pull request.

Unfortunately the initial idea of having some automatic code formatting remains open since this is pretty much a feature request for checkstyle from the beginning. I strongly believe that this auto formatting across multiple IDEs is still an issue and not easily achievable, however with a common check included I feel confident to be alerted if the code style is somehow not fitting into the project and thus will be closing this issue.
