### ISSUE TITLE
Inconsistency in dirty state

### ISSUE THREAD

**Issue by autayeu** [ktoso/maven-git-commit-id-plugin#234]
Got this in build logs:
```
[INFO] Repo is in dirty state [false]
[INFO] git.commit.id.describe 9fc943a
[INFO] git.commit.id 9fc943ac73c89ff05eda679774ede4c1b358ccd7
[INFO] git.commit.id.abbrev 9fc943a
[INFO] git.dirty true
```

First and last lines seem to be inconsistent...

**Comment by mvitz** [comment]
Above the first log output is a comment
```
// Git describe doesn't mind about untracked files when checking if
// repo is dirty. JGit does this, so we cannot use the isClean method
// to get the same behaviour. Instead check dirty state without
// status.getUntracked().isEmpty()
```

The value of git.dirty is calculated by calling:
```
...
return !gitObject.status().call().isClean();
...
```

I'm not sure what do there, but it seams copying the logic from the first dirty state calculation
```
boolean isDirty = !(status.getAdded().isEmpty()
        && status.getChanged().isEmpty()
        && status.getRemoved().isEmpty()
        && status.getMissing().isEmpty()
        && status.getModified().isEmpty()
        && status.getConflicting().isEmpty());
```
to the second should be the right thing to do?

**Comment by autayeu** [comment]
Perhaps in addition to synchronizing two ways so that they agree one way or another, a nice extra would be to report untracked files explicitly. Just presence flag or maybe even a list. Untracked files might influence build if the build is not written carefully.

**Comment by ktoso** [comment]
As a first step let's make them consistent – would you like to submit a PR fixing this issue @autayeu?
Seems like making the latter into a static utility method and reuse it would make the most sense here AFAICS, unless I understood the state of your repo wrong.

**Comment by mvitz** [comment]
I started to implement this but found another problem:

I expect the jGit and native Git implementation to behave identical.

If I have an untracked file present and use the plugin the following output is presented:
__jGit__
```
...
[INFO] pl.project13.maven.git.log.MavenLoggerBridge - Repo is in dirty state [ false ]
[INFO] pl.project13.maven.git.log.MavenLoggerBridge - git.commit.id.describe v2.2.0-2-gc9dafa8
...
[INFO] pl.project13.maven.git.log.MavenLoggerBridge - git.dirty true
...
```

__native__
```
...
[INFO] pl.project13.maven.git.log.MavenLoggerBridge - git.commit.id.describe v2.2.0-3-gc0d95c5
...
[INFO] pl.project13.maven.git.log.MavenLoggerBridge - git.dirty true
...
```

If I a modified file:

__jGit__
```
...
[INFO] pl.project13.maven.git.log.MavenLoggerBridge - Repo is in dirty state [ true ]
[INFO] pl.project13.maven.git.log.MavenLoggerBridge - git.commit.id.describe v2.2.0-3-gc0d95c5-DEVEL
...
[INFO] pl.project13.maven.git.log.MavenLoggerBridge - git.dirty true
...
```

__native__
```
...
[INFO] pl.project13.maven.git.log.MavenLoggerBridge - git.commit.id.describe v2.2.0-2-gc9dafa8-DEVEL
...
[INFO] pl.project13.maven.git.log.MavenLoggerBridge - git.dirty true
...
```

Therefore the native Git implementation of describe (or isDirty) must be changed as well. What is the expected behaviour?

**Comment by autayeu** [comment]
Consistency sounds great!

Expected: To me expected would be "dirty" in the presence of untracked files. But maybe native git implementation has a reason. Does anyone know it? It would be nice to know it. And maybe report untracked files separately in case there is a good reason to consider the repo "clean" with untracked files just like native git implementation does.

**Comment by mvitz** [comment]
Tried to find something, and found #47 ;-)

**Comment by TheSnoozer** [comment]
This is indeed a simple inconsistency.
First of all the "native" git implementation does not tell you in the first place if the ``Repo is in dirty state [ true/false ]`` this only happens if you run the jgit-Implementation with the describe enabled.

And indeed the dirty check for the jgit differs-slightly:
1) first dirty-message (only printed when someone want's to run the git describe): https://github.com/ktoso/maven-git-commit-id-plugin/blob/master/src/main/java/pl/project13/jgit/DescribeCommand.java#L329
2) second dirty-message: https://github.com/ktoso/maven-git-commit-id-plugin/blob/master/src/main/java/pl/project13/maven/git/JGitProvider.java#L131

Based on the comments in 1) I would suggest to change the dirty to the same as it is as in https://github.com/ktoso/maven-git-commit-id-plugin/blob/master/src/main/java/pl/project13/jgit/DescribeCommand.java#L329
also I would either remove the additional log message weather the repo is dirty or not or would move it to a place where it will be printed regardless of jgit or native git.
