### ISSUE TITLE
Error when URI contains domain (backward slash).

### ISSUE THREAD

**Issue by n0c1ip** [ktoso/maven-git-commit-id-plugin#258]
When I build project localy everything works fine, but when its builds on TeamCity server I get error like: `Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.1:revision (get-the-git-infos) on project ProjectName: Could not complete Mojo execution...`, then I switch to verbose mode and figured out, that it happend when plugin try parse `git.remote.origin.url` from .git/config. In TeamCity this url looks like this:

```
[remote "origin"]
url = http://domainName\\userName@Server/Path/To/Project/
```

on loclal machine:

```
[remote "origin"]
url = http://Server/Path/To/Project/
```

**Comment by mvitz** [comment]
According to https://tools.ietf.org/html/rfc3986#section-3 a URI is constructed as:
```
      URI         = scheme ":" hier-part [ "?" query ] [ "#" fragment ]

      hier-part   = "//" authority path-abempty
                  / path-absolute
                  / path-rootless
                  / path-empty
```

The used `\\` therefore is in the `hier-part` and there in the `authority path-abempty` part. authority is defined as ```authority   = [ userinfo "@" ] host [ ":" port ]``` (see https://tools.ietf.org/html/rfc3986#section-3-2).

Therefore the `\\` belongs to the userinfo part (because it's before the `@`) which is defined as ```userinfo    = *( unreserved / pct-encoded / sub-delims / ":" )``` (see https://tools.ietf.org/html/rfc3986#section-3-2-1) where ```unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"``` (see https://tools.ietf.org/html/rfc3986#section-2.3) and ```pct-encoded = "%" HEXDIG HEXDIG``` (see https://tools.ietf.org/html/rfc3986#section-2.1) and ```sub-delims  = "!" / "$" / "&" / "'" / "(" / ")" / "*" / "+" / "," / ";" / "="``` (see https://tools.ietf.org/html/rfc3986#section-2.2).

Therefore the used `\\` is illegal for a valid URI and needs to be percent-escaped. This may be a bug in TeamCity.

**Comment by TheSnoozer** [comment]
@mvitz,
thank you very much for this valuable feedback!
Is there something we need to fix inside the plugin?

Maybe not failing when URL extraction is not working properly?
In this case how should we handle invalid URLs?

I would say in general a better error message would be handsome...

**Comment by PPazderski** [comment]
To add a new aspect on this issue: git allows local path as remote.<name>.url and for windows this is likely a path using backward slashes which results in the same issue described in op.

So you may consider to just return the `gitRemoteString` for invalid URLs instead of failing the build.

Possible workaround is to replace the remote urls backslashes with slashes which are mostly handled correct by windows.

**Comment by TheSnoozer** [comment]
This is indeed kinda ugly.

The plugin currently has a switch:
``` <failOnUnableToExtractRepoInfo>true</failOnUnableToExtractRepoInfo>```
it is true by default.

Technically the plugin fails to extract the repository information correctly or in a way that they might disclose passwords. Thus I feel this switch should take over control of what should happen inside the build.

* set to true => if the extraction / or manipulation of the URL fails the build fails since the information couldn't be extracted
* set to false => well obviously the build shouldn't fail now. But there are two different ways which would both be valid: 1) leave the URL blank / empty 2) return ``gitRemoteString`` and risk to possibly disclose passwords -- I personally would prefer an error message and leave it blank

**Comment by TheSnoozer** [comment]
Feedback based on this specific issue
===============================

After some testing I would claim that the plugin is working as expected.
As outlined in one of the first responses the URI is not properly encoded and thus I would expect the plugin to fail. I would recommend to report a bug to TeamCity to fix their encoding.

As outlined in my previous post the plugin can provide a workaround to fail the build with the ``<failOnUnableToExtractRepoInfo>true</failOnUnableToExtractRepoInfo>``-switch.

Case 1:
--------------------
```
git remote set-url origin http://domainName\\userName@Server/Path/To/Project/
<failOnUnableToExtractRepoInfo>false</failOnUnableToExtractRepoInfo>
```

Result:
```
Error message in Log (as expected), but build runs through.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

Case 2
--------------------
```
git remote set-url origin http://domainName\\userName@Server/Path/To/Project/
<failOnUnableToExtractRepoInfo>true</failOnUnableToExtractRepoInfo>
```

Result:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.332 s
[INFO] Finished at: 2017-07-29T00:43:28+02:00
[INFO] Final Memory: 15M/489M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.3-SNAPSHOT:revision (get-the-git-infos) on project git-commit-id-plugin: Could not complete Mojo execution...: java.net.URISyntaxException: Illegal character in authority at index 7: http://domainName\userName@Server/Path/To/Project/ -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
```

In regards of having git hosted locally:
==============================
Based on https://www.kernel.org/pub/software/scm/git/docs/git-push.html#URLS
The git-project can be hosted locally....I never saw this somewhere and would argue the use base but thats not the point here....the following syntaxes may be used for gitRemoteString:
* /path/to/repo.git/ 
* file:///path/to/repo.git/ 

Both is supported in the current version of the plugin (additional checks will be pushed right after...).
If you have a case that is not supported; please open a separate issue / ticket.
