### ISSUE TITLE
M2E Lifecycle Mapping default <runOnIncremental>true not a good idea

### ISSUE THREAD

**Issue by vorburger** [ktoso/maven-git-commit-id-plugin#269]
Hello, thanks for this cool Maven plugin!

It's great and very useful - but slows down workspace builds in Eclipse.. scanning non-trivial git repos has a price, and I'm not sure doing that at every incremental build is such a good idea.. how about changing the [runOnIncremental in lifecycle-mapping-metadata.xml](https://github.com/ktoso/maven-git-commit-id-plugin/blob/master/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml#L11) from its current default true to false?

It's of course possible to change this in a pom.xml in org.eclipse.m2e:lifecycle-mapping, or Eclipse ws/.metadata/.plugins/org.eclipse.m2e.core/lifecycle-mapping-metadata.xml - what I'm suggesting here is that the current default is perhaps sub-optimal ... if you do agree to change it, anyone who truly does want it to run in-IDE incrementally all the time, and who's willing to take the workspace build performance hit for it, can still re-enable it, just like I'm currently ignore it.

Would you welcome a contribution for this?

**Comment by TheSnoozer** [comment]
Hi,
thanks for your valuable feedback!
Based on https://wiki.eclipse.org/M2E_compatible_maven_plugins the runOnIncremental is the following:
> If <runOnIncremental/> is set to true, corresponding mojo will be executed during both full and incremental workspace builds. If set to false (the default), the mojo will be executed during full workspace build only. 

Currently I think the maven-git-commit-id-plugin should be executed with full and incremental builds as well. My reasoning behind this is that with my favorite environment the full build will only be triggered when asked for. Thus let's just imagine I have a clean project and trigger a full build. This will then trigger the maven-git-commit-id-plugin and generate the git properties accordingly. However now I find a bug, fix it and commit it. With the runOnIncremental set to true the git properties will be updated to the correct new commit version. However when using the runOnIncremental set to false the  git properties won't be updated since no full build has been. This will result in outdated information. Not sure if someone really relies on the properties that had been generated by Eclipse / Idea but I kinda feel this should be as is......

Also when talking about "the plugin is slow" - have you tried the native git implementation? :-)

**Comment by michaldo** [comment]
I agree with @vorburger that runOnIncremental should be false. maven-git-commit-id-plugin  is similar to maven-javadoc-plugin. As application developer I don't care my javadocs are outdated. I also don't care git.properties are outdated.
As application developer I want incremental as fast as possible

**Comment by TheSnoozer** [comment]
Was added and will be released (sometime) with version 2.2.3
