### ISSUE TITLE
Enable @TheSnoozer to release the plugin

### ISSUE THREAD

**Issue by TheSnoozer** [ktoso/maven-git-commit-id-plugin#313]
as outlined in https://github.com/ktoso/maven-git-commit-id-plugin/issues/300:

> I also propose to fix the root issue here, I'm ok with adding @TheSnoozer to sonatype's OSS staging repo for pl.project13 so you could release this plugin at will. Please register on this issue tracker https://issues.sonatype.org/browse/OSSRH-1324 and give me your sonatype username and I'll ask for things to be set up.

**Comment by ktoso** [comment]
Right, let's do this 👍

**Comment by TheSnoozer** [comment]
Tried to find something matching:
https://issues.sonatype.org/secure/ViewProfile.jspa?name=TheSnoozer
;-)

**Comment by ktoso** [comment]
Requested the permissions: https://issues.sonatype.org/browse/OSSRH-1324 :)

—
Konrad `kto.so` Malawski
Akka <http://akka.io> @ Lightbend <http://lightbend.com>

On 29 August 2017 at 07:21:26, TheSnoozer (notifications@github.com) wrote:

Tried to find something matching:
https://issues.sonatype.org/secure/ViewProfile.jspa?name=TheSnoozer
;-)

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/ktoso/maven-git-commit-id-plugin/issues/313#issuecomment-325499948>,
or mute the thread

**Comment by ktoso** [comment]
@TheSnoozer can now release this plugin :)

Make sure you get a gpg key that sonatype sees and then you can:

- `mvn release:prepare` (make sure to match tag name with current style)
- `mvn release:perform`
- then go to oss.sonatype.org log in there and go to the staging repositories, there will be the plugin, you have to first `close` and then `release` it if validation passed.

Let me know when in case you'd need to release next time anyway tho :)

**Comment by TheSnoozer** [comment]
Thanks! :-)
In case I need to deploy I guess I'll also check into the http://central.sonatype.org/pages/ossrh-guide.html

**Comment by TheSnoozer** [comment]
Worked like a charm:
see https://github.com/ktoso/maven-git-commit-id-plugin/issues/333

Thanks :-)

**Comment by ktoso** [comment]
Awesome :)
