### ISSUE TITLE
Don't require Maven patch version

### ISSUE THREAD

**Issue by cbismuth** [ktoso/maven-git-commit-id-plugin#316]
Hi,

Is really useful to depend on Maven 3.1.1 or would it be enough to depend on 3.1.0 and let the end-user patch his own installation?

Thanks,
Christophe

**Comment by TheSnoozer** [comment]
Hi,
I might not understand the full need of this....

Regardless to answer your question:
The plugin need to depend on some Maven version and this version can not be set by the user.
It furthermore can not be set by the user, since its set inside the [pom of the plugin](https://github.com/ktoso/maven-git-commit-id-plugin/blob/master/pom.xml#L57) and required for building the plugin.

Please checkout the [README](https://github.com/ktoso/maven-git-commit-id-plugin/#plugin-compatibility-with-maven) to see what maven version are required to run the plugin. If you still rely on an old 3.1.0 version I'd recommend the plugin version `2.1.13`, or if possible to upgrade your maven version to `3.1.1` or anything more recent.

**Comment by cbismuth** [comment]
Hi,

Yes we have an outdated CI installation. I think there might not be any required API change or blocking bug on your side, so why not depend on 3.1.1 and not 3.1.0?

I'll upgrade our CI dependencies, but this question is more about good practice in plugin development: why not depend on the lowest required version of Maven?

**Comment by TheSnoozer** [comment]
> I think there might not be any required API change or blocking bug on your side, so why not depend on 3.1.1 and not 3.1.0?
Knowing Maven I wouldn't assume this - you never know ;-)

Regardless as a Plugin Developer I would argument the other way round:
Why can't you update your maven-version to anything more recent? If you can use a maven version that was released on 2013-10-04 (about 4 years ago) what system are you using? Is this still supported by anything?
Usually with updates more features are being shipped or security patches fixed and thus I would rather tend and say why not upgrade to the latest and greatest? 

Regardless of this I kinda understand where you are coming from and I can check locally if I see an impact if the version changes, but knowing Maven there is 1209831092 trillion things that are breaking with this simple version change. Furthermore I would also argue why not go back even further and support the 3.0 version then. When going back to 3.0 I would assume even more breaks but I'll check on this...

**Comment by TheSnoozer** [comment]
Just as a personal note:
The maven surfire-plugin uses a somewhat mix of [`<mavenVersion>2.2.1</mavenVersion>`](https://github.com/apache/maven-surefire/blob/master/pom.xml#L89) and [`<mavenPluginPluginVersion>3.3</mavenPluginPluginVersion>`](https://github.com/apache/maven-surefire/blob/master/pom.xml#L91) this requires a more in-depth investigation what plugin versions needs to be old and what plugin versions need to be "newer" to avoid any issues.

**Comment by TheSnoozer** [comment]
Thanks for your report.
The plugin will now support everything from Maven 3.X (including 3.0) and onwards. I won't provide any support for any Maven 2.X since its deprecated.
In general local tests didn't yield any issues and travis build is configured so it verifies the functionality of some maven versions. Personally testing every maven version would be somewhat against the fair use of travis and unless there is anything in specific that only appears on a specific maven version it might even be a maven bug.

Let's cross fingers that this doesn't break anything.

Maven 3.X will be supported with the next version 2.2.4

**Comment by cbismuth** [comment]
Woah, thank you for the hard work and deep investigations @TheSnoozer and @ktoso  :+1:
