### ISSUE TITLE
Differences between git.tags and git.closest.tag.name

### ISSUE THREAD

**Issue by huksley** [ktoso/maven-git-commit-id-plugin#348]
### Expected Behavior

* git.tags should reflect git.closest.tag.name

### Current Behavior

For some repositories I get git.tags field, for some other repositories, git.closest.tag.name.

### Environment (for bugs only)

  * GitLab.com
 * git native/jgit tried with same result
 * mvn clean package -> target/classes/git.properties

**Comment by TheSnoozer** [comment]
Hi,
thanks for reporting your issue here.

I believe what you are reporting here is a misunderstanding, unless you have a specific repository where a specific bug can be reproduced (e.g. git native produces something else than jgit).

For some more clarifications:

* For the `git.tags property` we basically execute [git tag --contains](https://git-scm.com/docs/git-tag#git-tag---containsltcommitgt). Based on the documentation it would mean `Only list tags which contain the specified commit` (which is most cases HEAD). The `git.tags` is pretty much the same feature what github/gitlab has where it shows for each commit in what tags those are included:
![example](https://user-images.githubusercontent.com/6849390/30434691-e40e96e6-9935-11e7-9232-037fb8e4e1dc.png)
Unless your HEAD is on a tag the expectation is that this property is empty.
* For the `git.closest.tag.name` we try to find the closest tag-name (something along the lines `git describe HEAD --abbrev=0`)

For some cases it is true that `git.closest.tag.name` is also reflected inside `git.tags`, but in most cases where you build your untagged HEAD `git.tags` will return an empty result, whereby `git.closest.tag.name` returns the tag name that is closest to the current commit.


If you still believe this is an error, I'd ask to provide more context where it can be reproduced (unfortunately it has loads of reasons why we ask for so much stuff):
```
<!-- The following needs to be completed as best as possible **for bugs only** -->
### Steps to Reproduce (for bugs only)
<!-- If describing a bug, please include the **full** configuration of the plugin -->
<!-- If describing a bug, is there a (public) project where this issue can be reproduced? -->

### Environment (for bugs only)
<!-- If describing a bug, please provide the plugin version is being used -->
<!-- If describing a bug, please provide the Java-Version is being used (please include details about oracle-jdk VS open-jdk) -->
<!-- If describing a bug, please provide the Maven-Version is being used (output of ``mvn --version``) -->
<!-- If describing a bug, please let us know on what Operating System you experience the bug (on Linux run ``lsb_release -a``) -->
<!-- If describing a bug, please let us know in what context maven is being executed (e.g. inside Windows Terminal, Powershell, Git Bash, /bin/bash, ...) -->
<!-- If describing a bug, please let us know how maven is being executed (e.g. ``mvn clean deploy`` VS ``mvn deploy:deploy``) -->
```
