### ISSUE TITLE
use generated-sources folder for the generated file

### ISSUE THREAD

**Issue by stefaneicher** [ktoso/maven-git-commit-id-plugin#358]
Hi,

you may better want to use this ${project.build.directory}/generated-sources/git as a default.

<generateGitPropertiesFilename>${project.build.directory}/generated-sources/git/git.properties</generateGitPropertiesFilename>

and not
                    <generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties</generateGitPropertiesFilename>
because the is where the compiles stuff should be. for example Intellij delete this folder which is ok if Intellij compiles the classes again ( but it does not regenerate sources ).

Thus I think the right place for those generated files should be the one 
${project.build.directory}/generated-sources/git/git.properties

Regards Stefan

**Comment by TheSnoozer** [comment]
Mhh I see your point why the ``generated-sources`` might be a better fit, however I highly doubt that changing the default for **every build** would be the correct answer to solve the problem. The main reason is that everyone uses a different IDE and might have a different build setup. The plugin configuration allows to change the value for your builds so from that standpoint this discussion is really about changing the default.

Just a quick though that needs more clarification and I see as additional potential thinks that would break
- How does this problem look for other IDEs? Not everyone is using IDEA
- Whats really the problem here? Your dev build inside IDE is not having the correct git commit or no information about your git directory. I truly hope that you don't build your artifacts with an IDE so don't see anything breaking in "production" (aka building with maven directly).
- How hard is it to tell your IDE (or any other IDE) about that special source folder? Is it a thing that is also integrated and will be recognized by default or is there any manual effort involved (e.g. like outlined here https://stackoverflow.com/a/5171035)
- Would there any programmatically changes required to load the file? (aka would there anything change in loading the properties in java with ``getClass().getClassLoader().getResource("git/git.properties")`` or would the additional ``generated-sources`` need to be copied with a copy task to somewhere (where?) so this remains functional?

**Comment by TheSnoozer** [comment]
I'd suggest to set the location inside your configuration.
I would prefer not to change the defaults since it raises too many questions / concerns and breaks backward compatibility.
