### ISSUE TITLE
allow variables in the shouldMatchTo validation

### ISSUE THREAD

**Issue by sorin-costea** [ktoso/maven-git-commit-id-plugin#367]
I'd like to be able to use variables in the matcher, like this:

```
                        <validationProperty>
                            <name>correct java version</name>
                            <value>jdk${java.version}</value>
                            <shouldMatchTo>${file.java.archivedName}</shouldMatchTo>
                        </validationProperty>

```
(right now the shouldMatchTo expression goes directly into a Parser and is treated as regex...)

**Comment by TheSnoozer** [comment]
Hi,
thanks for your report.
I'm assuming ${file.java.archivedName} is the one that causes the issue here.
Where does the variable come from?

How does it look like when you use the variables in other plugins (similar to this):
```
<plugin>
				<artifactId>maven-antrun-plugin</artifactId>
				<version>1.8</version>
				<executions>
					<execution>
						<phase>package</phase>
						<configuration>
							<target>
								<echo>java.version: ${java.version}</echo>
								<echo>file.java.archivedName: ${file.java.archivedName}</echo>
							</target>
						</configuration>
						<goals>
							<goal>run</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```

If its not getting resolved here, its simply not visible to the POM and thus wont result in the proper replacement.In theory this is not even an issue of the plugin, its an issue what variables are visible inside the pom itself.

**Comment by TheSnoozer** [comment]
Hi,
did you got this working?

**Comment by TheSnoozer** [comment]
Works fine on my end.
~ Closing ~
Feel free to reopen if it still does not work.
